In [ ]:
! pip install pandas scikit-learn numpy
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("mainSimulationAccessTraces.csv")

print(data.shape)

(357952, 13)

In [3]:
print(data.columns)

Index(['sourceID', 'sourceAddress', 'sourceType', 'sourceLocation',
       'destinationServiceAddress', 'destinationServiceType',
       'destinationLocation', 'accessedNodeAddress', 'accessedNodeType',
       'operation', 'value', 'timestamp', 'normality'],
      dtype='object')

In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357952 entries, 0 to 357951
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   sourceID                   357952 non-null  object
 1   sourceAddress              357952 non-null  object
 2   sourceType                 357952 non-null  object
 3   sourceLocation             357952 non-null  object
 4   destinationServiceAddress  357952 non-null  object
 5   destinationServiceType     357952 non-null  object
 6   destinationLocation        357952 non-null  object
 7   accessedNodeAddress        357952 non-null  object
 8   accessedNodeType           357804 non-null  object
 9   operation                  357952 non-null  object
 10  value                      355902 non-null  object
 11  timestamp                  357952 non-null  int64
 12  normality                  357952 non-null  object
dtypes: int64(1), object(12)
memory usage: 35.5+ MB
None

Nettoyage et simplification

In [5]:
drop_cols = [
    "sourceID",
    "sourceAddress",
    "destinationServiceAddress",
    "accessedNodeAddress"
]

data.drop(columns=drop_cols, inplace=True)

Vérification des valeurs manquantes

In [6]:
print(data.isna().sum())

sourceType                   0
sourceLocation               0
destinationServiceType       0
destinationLocation          0
accessedNodeType           148
operation                    0
value                     2050
timestamp                    0
normality                    0
dtype: int64

In [7]:
print(data['normality'].value_counts())

normality
normal                           347935
anomalous(DoSattack)               5780
anomalous(scan)                    1547
anomalous(malitiousControl)         889
anomalous(malitiousOperation)       805
anomalous(spying)                   532
anomalous(dataProbing)              342
anomalous(wrongSetUp)               122
Name: count, dtype: int64

In [8]:
#  0 = normal, 1 = anomalous
data['normality'] = data['normality'].apply(lambda x: 0 if x == 'normal' else 1)

# Check counts
print(data['normality'].value_counts())

normality
0    347935
1     10017
Name: count, dtype: int64

In [9]:
print(data['value'].value_counts())

value
1                    57047
0                    50282
false                25966
true                 14460
10                    9635
                     ...
1.521217446778E12        1
1.521220297057E12        1
1.521220308496E12        1
1.521220325816E12        1
1.521225180883E12        1
Name: count, Length: 10623, dtype: int64

Détection Sémantique : probleme Value

In [10]:
np.set_printoptions(threshold=np.inf)
print(data['value'].unique())

['none' '20.0464' '1' '1.52121675521E12' '19.8391' '19.9088' '19.9523'
 '1.521216758314E12' '19.8185' '20.0005' '0' '20.4750' '20.2078' '20.1757'
 '19.7536' '19.7719' '20.4103' '19.8609' '20.1794' '20.0372' '20.1058'
 '19.7941' '19.9142' '20.3042' '20.1346' '19.7922' '20.1731' '20.1458'
 '19.7587' '20.1929' '20.4331' '19.6966' '19.6209' '19.9143' '19.6963'
 '19.5072' '20.4032' '1.521216770002E12' '19.9860' '20.2714' '20.3664'
 '19.6491' '19.6007' '19.7861' '20.2914' '19.8480' '20.3901' '19.5935'
 '19.9351' '20.4009' '19.5693' '19.9501' '20.3104' '19.6382' '20.2557'
 '19.7876' '20.0605' '19.9950' '20.0012' '20.0302' '19.5702' '20.3979'
 '19.6520' '19.8319' '20.4505' '19.6254' '20.0283' '19.6995' '20.1410'
 '20.4480' '20.1077' '1.521216782996E12' '19.8770' '19.9342' '20.4309'
 '19.8495' '20.4105' '20.1277' '19.7564' '19.8989' '19.5407' '20.1878'
 '19.5759' '19.8346' '20.4532' '19.6320' '19.8776' '19.6612' '19.9497'
 '20.2760' '19.6815' '20.0496' '20.1338' '20.2199' '20.2705' '20.2783'
 '19.8589' 'false' '20.1928' '20.4416' '19.6395' '19.5472' '19.7862'
 '20.3430' '20.0910' '20.0299' '20.2464' '19.7993' '20.3671' '20.0516'
 '10' '20.1174' '20.0000' '20.0521' '19.6478'
 'org.ds2os.vsl.core.utils.AddressParameters@463d9146'
 'org.ds2os.vsl.core.utils.AddressParameters@699d52f5'
 'org.ds2os.vsl.core.utils.AddressParameters@273343f8' '20.4989' '19.7072'
 '19.5762' 'org.ds2os.vsl.core.utils.AddressParameters@181ae4a8' '20.3848'
 '19.5774' '19.5849' '9'
 'org.ds2os.vsl.core.utils.AddressParameters@5c494e7d' '20.1150' '19.8014'
 '20.1056' '20.1907' 'org.ds2os.vsl.core.utils.AddressParameters@6876d7bb'
 'org.ds2os.vsl.core.utils.AddressParameters@4ff97c45' '20.3084' '20.0278'
 '19.7077' 'org.ds2os.vsl.core.utils.AddressParameters@3ebb34ed' '20.4617'
 '20.1326' '20.4977' '20.0972' '19.8093' '20.3011' '20.3369' '20.0796' '8'
 'org.ds2os.vsl.core.utils.AddressParameters@2c82b391' '19.7635'
 'org.ds2os.vsl.core.utils.AddressParameters@61ba9b2b' '20.3052' '20.1297'
 'org.ds2os.vsl.core.utils.AddressParameters@715cced' '19.7849' '19.9097'
 '20.1704' '20.3000' '19.9473' '20.1170' '20.4190' '20.3016' '19.8582'
 '19.5147' '20.1748' '20.0985' '19.6181' '19.5581' '20.4914' '20.0884' '7'
 '19.6475' '20.1997' '20.3385' '20.4238' '20.0639' '19.8990' '20.3349'
 '20.3173' '20.3155' '20.3616' '20.4847' '20.0776' '19.8551' '20.0742'
 '19.5857' '20.3542' '20.3478' '19.9817' '20.1096' '19.9075' '6' '20.0022'
 '20.2280' '20.3655' '20.1853' '19.7416' '19.5997' '19.7391' '19.5907'
 '19.7147' '20.3355' '19.8560' '20.2799' '20.1541' '20.0079' '19.8745'
 '20.0983' '19.8283' '20.0601' '20.3693' '20.3950' '5' '20.0930' '20.4418'
 '20.0331' '19.9062' '19.9935' '20.4034' '19.5439' '20.3569' '19.9693'
 '20.4835' '20.1695' '19.9555' '19.8472' '20.2250' '20.3934' '20.4167'
 '19.6667' '20.3038' '20.1393' '4' '19.9383' '20.4855' '19.5471' '20.3923'
 '19.9326' '19.7903' '20.1380' '19.7647' '19.6076' '19.6518' '19.6150'
 '19.8362' '20.2757' '20.0409' '20.3160' '20.4667' '19.7916' '20.4487'
 '20.4166' '19.8872' '3' '20.4056' '20.3770' '19.6751' '20.1646' '20.4783'
 '20.0763' '19.7286' '19.5444' '20.1911' '19.5634' '20.3563' '19.6578'
 '19.8434' '19.8640' '19.5034' '20.0350' '19.5980' '20.3255' '20.2786'
 '19.5588' '20.0864' '2' '20.2033' '20.4614' '19.5314' '19.9533' '20.4605'
 '20.3292' '20.3327' '19.5303' '19.5259' '19.7311' '20.4420' '19.6167'
 '20.4628' '19.7266' '19.6727' '19.8326' '19.8329' '20.0903' '20.2295'
 '20.0838' '20.2577' '19.7488' '19.9852' '19.6140' '20.4312' '19.9407'
 '20.4756' '19.6039' '19.5781' '19.7041' '20.0430' '20.3353' '20.3144'
 '20.4157' '20.2488' '19.6653' '19.8896' '19.5867' '20.3640' '20.2427'
 '20.3873' '20.4012' '20.0475' 'true' '19.5362' '19.9071' '19.5037'
 '19.5173' '20.1402' '20.0764' '19.5453' '20.1664' '19.6876' '20.3243'
 '19.7507' '20.1628' '19.6888' '20.2322' '19.5419' '19.8929' '20.2539'
 '20.1952' '19.6918' '20.0533' '20.1389' '20.3776' '19.9217' '19.6511'
 '20.2062' '19.8975' '19.9006' '19.7501' '19.8414' '19.9420' '20.4328'
 '19.8493' '20.2343' '20.2791' '19.6754' '19.6608' '20.4040' '19.5428'
 '19.8177' '20.3991' '20.3433' '19.6193' '20.3788' '19.6854' '19.6542'
 '20.2307' '20.1937' '19.5437' '20.4702' '20.4217' '20.3715' '19.7602'
 '20.3464' '20.0368' '20.2335' '20.4259' '20.3605' '19.9718' '20.0093'
 '20.0453' '20.0213' '19.8485' '20.0957' '20.3893' '19.5226' '20.2166'
 '19.6762' '20.2355' '20.0049' '20.2643' '19.6017' '19.9562' '19.9731'
 '20.0818' '19.7673' '19.7216' '19.5706' '19.8126' '19.9946' '19.6806'
 '20.1197' '20.4934' '20.4120' '19.8996' '20.2361' '19.8906' '19.7229'
 '19.9211' '20.4540' '19.5714' '19.8804' '20.2221' '20.1451' '19.7209'
 '20.1864' '20.1613' '20.4215' '19.5650' '19.8454' '19.6371' '20.4885'
 '20.0391' '19.5222' '19.9168' '20.1553' '19.6026' '20.0945' '19.8841'
 '20.1753' '19.5933' '19.7467' '19.5612' '20.1563' '19.5748' '20.1849'
 '19.8066' '20.0627' '20.2658' '20.4601' '20.4161' '20.3714' '20.2421'
 '19.7968' '19.8659' '20.2327' '20.4194' '19.9985' '20.1620' '20.2192'
 '19.5119' '20.2076' '20.0731' '20.4959' '20.0380' '19.7012' '19.6249'
 '19.8274' '20.1261' '20.2830' '20.4968' '20.3545' '19.6624' '20.1657'
 '19.7785' '20.2420' '19.9866' '20.3581' '19.7446' '19.6112' '19.7973'
 '19.5365' '20.0515' '19.5289' '19.8893' '20.2720' '19.9733' '19.7300'
 '19.5027' '19.9035' '20.1835' '19.7728' '19.9261' '20.0878' '20.1161'
 '19.8032' '19.6256' '19.5528' '20.1035' '20.3376' '19.6716' '20.4970'
 '20.0023' '20.2894' '19.5436' '19.6402' '19.9234' '19.5020' '20.0490'
 '20.2272' '20.2001' '19.6044' '20.3987' '19.8903' '19.6108' '19.9795'
 '20.2819' '19.8375' '20.2547' '19.8629' '20.1139' '19.6172' '20.4769'
 '20.0871' '19.6492' '19.5548' '20.3864' '20.3920' '19.8916' '19.6676'
 '20.0956' '20.4867' '20.3555' '19.6463' '20.2998' '20.3772' '19.6548'
 '20.0741' '19.5358' '20.2956' '20.3307' '19.6425' '19.7550' '20.2781'
 '19.9871' '20.2536' '19.9413' '20.4493' '20.3921' '19.6760' '20.3753'
 '19.5694' '19.9302' '1.521216841986E12' '19.6235' '19.6763' '19.9680'
 '20.4004' '19.8697' '19.8836' '20.4731' '19.7628' '19.5312' '20.0534'
 '19.5981' '20.1529' '19.7703' '19.5565' '20.3489' '19.9715' '20.3494'
 '19.6094' '19.8259' '19.9015' '20.4912' '20.3695' '20.0667' '19.6190'
 '20.2656' '20.1368' '20.4854' '20.0609' '19.8795' '19.8102' '19.8435'
 '19.9148' '20.0783' '19.6655' '19.7182' '19.6168' '19.6703' '19.6709'
 '20.0991' '20.1447' '20.3629' '20.4319' '19.9664' '20.1397' '19.7461'
 '20.1486' '19.8402' '19.7528' '19.6887' '20.1401' '19.5057' '19.5888'
 '20.2125' '19.7513' '20.3947' '19.9627' '19.7829' '19.5038' '19.9246'
 '20.0078' '20.1714' '19.8134' '19.7761' '19.8860' '20.2582' '19.9219'
 '19.7844' '19.9662' '19.5414' '20.4093' '19.6101' '20.1869' '19.7908'
 '19.8666' '20.4877' '19.8076' '20.3785' '19.9723' '20.3549' '20.4832'
 '19.7676' '20.0355' '20.1344' '20.4823' '19.5456' '19.5442' '20.4634'
 '19.9753' '19.9072' '19.8642' '19.7951' '20.2471' '19.9518' '20.2447'
 '19.6947' '20.2365' '19.6505' '19.8979' '19.8194' '20.1290' '20.0752'
 '19.9355' '20.2005' '20.1502' '19.7870' '19.6953' '20.2246' '19.6790'
 '20.0402' '19.9522' '19.6622' '19.6064' '19.7373' '19.5062' '19.8484'
 '19.7352' '20.3684' '20.0259' '19.7599' '19.6414' '19.7183' '20.4484'
 '20.0981' '19.5514' '19.8376' '20.3669' '20.2356' '19.8293' '20.1051'
 '19.7285' '20.1143' '19.5903' '19.6165' '19.9078' '20.2168' '19.9575'
 '20.3574' '20.4311' '20.4439' '19.7414' '19.8155' '19.8596' '20.1611'
 '19.5546' '19.6900' '19.9962' '19.9367' '20.4258' '19.9012' '19.5585'
 '19.6558' '19.9970' '20.3717' '20.1587' '20.3606' '19.6948' '20.0088'
 '20.1542' '20.4907' '19.9254' '19.8729' '20.1222' '20.4080' '19.7977'
 '19.7264' '19.9412' '19.7815' '20.4762' '19.8566' '19.8016' '19.9144'
 '20.1825' '20.3335' '19.8995' '20.2407' '19.8366' '19.7451' '20.1517'
 '20.0056' '20.4674' '20.4349' '20.4576' '19.8585' '19.6247' '20.1800'
 '20.2762' '20.0774' '20.2394' '20.1000' '20.0998' '20.4948' '19.6628'
 '20.4233' '19.9031' '19.5161' '20.3179' '20.3890' '19.5266' '19.5351'
 '20.2253' '20.0543' '20.0767' '20.3183' '19.9117' '19.5017' '19.7875'
 '20.2805' '19.5311' '20.2508' '20.3299' '20.1623' '20.1066' '19.7669'
 '20.1007' '20.2960' '20.1506' '20.0334' '19.9806' '20.1163' '20.0495'
 '20.0066' '19.8807' '20.2984' '19.8670' '20.1055' '20.2082' '19.6536'
 '19.9727' '19.7381' '20.2035' '19.6040' '20.2905' '19.6191' '20.1441'
 '19.9262' '19.9531' '20.4642' '20.1631' '20.2758' '20.4982' '19.8413'
 '20.4715' '19.5333' '20.0034' '20.3620' '20.3888' '19.6928' '19.9424'
 '20.1106' '19.7153' '19.5956' '19.9184' '20.4849' '20.1308' '19.6304'
 '20.4550' '20.0861' '20.0751' '20.4820' '20.0806' '20.3568' '19.8163'
 '19.5185' '20.4512' '20.4956' '20.4693' '20.3541' '20.4897' '19.7289'
 '20.0104' '20.4422' '20.1065' '19.9282' '20.4141' '20.0227' '20.0687'
 '20.2726' '19.7000' '19.5532' '19.6965' '19.6694' '19.7048' '20.3735'
 '20.3043' '20.4438' '20.2999' '19.5829' '19.7549' '19.6955' '19.6845'
 '20.2841' '20.4875' '19.8449' '19.5098' '19.9170' '20.0473' '19.9156'
 '19.6898' '19.8020' '19.8328' '20.0850' '20.0680' '20.3814' '20.2663'
 '19.9701' '20.4946' '19.5818' '20.4035' '20.3305' '20.0426' '19.7706'
 '20.1425' '20.2234' '20.0144' '20.0440' '20.3240' '20.0888' '20.0762'
 '20.1327' '20.3169' '20.2610' '19.5302' '19.5622' '20.1978' '20.3435'
 '20.0411' '19.8489' '20.0054' '20.1177' '19.5788' '20.1504' '20.1735'
 '19.9902' '19.5115' '19.7780' '19.8653' '19.5464' '19.8418' '20.1742'
 '20.1148' '20.4249' '20.4555' '20.1353' '19.8817' '19.6337' '20.3293'
 '20.4336' '20.2489' '19.8187' '20.4113' '20.3649' '20.4054' '19.7318'
 '19.8930' '19.7100' '19.6099' '20.3107' '20.3849' '19.7293' '20.4813'
 '19.8149' '19.8612' '20.3060' '19.5590' '19.9976' '20.2558' '20.2627'
 '19.5486' '20.1900' '19.8610' '20.4763' '20.1042' '19.9417' '19.6905'
 '19.6921' '20.1474' '20.1349' '19.6949' '19.7061' '20.2728' '19.6832'
 '20.2505' '19.6345' '20.2472' '19.9046' '19.9814' '20.3761' '19.9586'
 '20.4341' '19.5982' '19.7622' '19.7808' '19.9294' '19.8128' '19.8591'
 '19.9226' '19.6111' '20.0617' '20.2384' '19.8637' '19.5540' '19.9882'
 '20.1895' '20.1822' '20.1412' '20.4447' '20.1490' '19.9178' '20.2435'
 '20.3314' '20.0873' '20.0630' '19.8645' '20.2303' '19.6267' '20.0188'
 '19.6561' '20.2790' '20.4114' '20.3409' '20.2548' '19.6268' '20.1485'
 '19.5208' '20.0063' '20.0052' '19.6302' '19.9273' '20.4631' '19.8148'
 '20.3484' '20.3861' '19.7448' '20.1293' '19.9468' '19.7452' '19.7948'
 '20.3828' '19.9102' '19.8992' '19.9831' '19.5411' '19.7263' '19.9430'
 '19.7325' '20.4134' '20.0618' '19.8918' '19.8255' '20.0610' '20.4087'
 '20.1571' '20.3841' '19.9030' '19.5053' '20.3805' '19.7560' '19.9582'
 '20.2049' '19.5194' '20.1371' '19.7813' '19.6770' '20.4640' '19.7338'
 '20.0153' '20.0347' '20.1930' '20.0483' '20.2904' '19.9730' '20.2835'
 '19.5352' '20.4637' '19.9221' '19.5019' '19.8655' '19.8867' '20.2110'
 '19.5570' '19.5797' '19.5558' '20.4139' '19.8144' '19.5429' '20.3171'
 '20.1097' '20.1351' '19.8914' '19.7944' '19.7115' '19.9885' '19.6030'
 '19.7186' '19.7987' '20.2128' '19.8067' '19.9122' '20.4049' '20.3525'
 '19.7225' '19.9370' '20.1153' '20.0748' '20.2050' '20.3231' '19.5646'
 '20.4647' '19.5039' '19.8608' '19.8385' '20.4101' '19.5999' '20.4426'
 '20.2989' '20.0693' '20.0346' '20.0703' '20.3493' '19.9055' '19.8086'
 '20.4902' '20.3137' '19.7548' '20.4703' '20.1711' '20.2265'
 '1.521216899605E12' '20.2339' '20.2794' '20.0025' '20.3781' '19.9757'
 '20.2879' '20.1572' '20.1658' '19.6858' '19.7863' '20.1118' '19.5403'
 '19.5848' '19.9008' '20.2075' '19.5081' '19.9622' '20.3362' '20.0551'
 '20.4500' '19.8545' '19.6873' '19.6784' '20.4648' '20.3773' '20.0068'
 '20.2070' '19.6251' '19.6714' '19.6315' '20.1858' '20.2485'
 '1.521216902949E12' '20.3324' '19.6600' '20.3673' '20.1632' '19.6828'
 '19.5220' '20.0647' '19.6441' '19.6381' '20.2008' '19.6466' '19.7661'
 '19.9223' '20.3168' '20.3280' '20.0658' '19.9347' '20.1124' '20.0911'
 '1.521216905597E12' '20.4654' '19.6674' '20.1833' '20.1219' '20.4075'
 '20.3269' '20.2709' '20.2697' '20.3515' '20.4450' '20.4057' '20.4099'
 '20.4752' '19.5746' '19.8622' '19.7079' '20.0578' '19.9559' '19.8548'
 '19.9416' '19.9697' '20.1883' '19.6471' '19.8765' '20.4021' '20.1548'
 '19.6318' '20.0735' '19.8962' '20.4350' '19.9019' '20.3125' '19.7038'
 '19.8007' '20.4672' '20.3163' '20.3364' '19.7008' '19.9496' '20.3277'
 '20.1084' '20.2419' '19.6469' '20.1637' '19.7214' '19.7744' '19.7608'
 '19.9798' '19.9466' '20.4182' '19.7626' '20.0222' '19.7505' '20.4151'
 '19.7470' '19.8921' '19.6096' '20.1460' '20.4404' '20.3017' '19.8261'
 '20.1619' '20.2702' '20.2822' '19.6957' '19.6781' '20.0954' '19.8561'
 '20.3091' '19.7888' '20.0594' '20.0718' '20.1787' '20.2312' '20.4687'
 '20.4966' '19.9572' '19.5016' '19.7555' '20.1863' '19.6472' '19.8708'
 '19.5840' '20.0305' '19.7962' '19.6615' '19.5524' '1.521216915966E12'
 '20.3266' '20.2591' '19.5334' '19.6010' '20.0067' '20.0518' '19.5737'
 '20.1755' '19.9335' '19.9379' '19.7319' '20.2342' '19.5381' '20.3691'
 '20.1464' '20.0613' '19.7099' '19.7735' '19.5085' '20.3295' '19.5279'
 '19.9179' '20.4915' '19.7982' '19.8809' '19.5555' '19.6065' '20.3090'
 '19.9242' '19.5391' '19.7125' '19.5359' '20.3634' '19.7155' '20.3473'
 '20.3946' '20.4230' '20.0920' '20.0470' '20.1901' '20.1762' '20.1971'
 '20.1957' '20.1413' '20.4713' '19.6732' '19.7031' '20.1456' '20.4743'
 '19.6572' '20.2487' '20.4385' '20.4203' '19.7117' '20.1260' '20.4585'
 '20.1335' '19.6073' '20.3195' '20.0771' '1.521216923287E12' '20.0103'
 '20.3387' '20.4671' '20.1110' '20.3912' '20.3863' '20.1556' '19.8455'
 '20.2264' '19.6522' '19.6734' '19.7393' '20.1567' '20.2228' '19.5810'
 '19.9604' '20.4742' '19.5367' '20.4489' '19.8452' '19.8230' '19.8055'
 '20.3862' '20.4535' '19.6514' '20.4441' '19.6045' '19.7598' '20.1855'
 '19.8252' '20.1189' '20.4552' '20.0313' '19.9174' '19.9561' '19.5624'
 '20.1659' '19.8947' '20.4332' '20.4432' '20.2103' '20.3396' '20.1712'
 '20.3273' '20.3659' '19.6092' '20.1040' '20.3533' '20.2208' '19.8386'
 '20.0904' '19.5743' '19.9414' '19.5137' '19.9663' '20.2348' '19.9878'
 '19.8117' '20.0204' '19.8724' '20.3228' '19.7188' '20.4327' '20.0622'
 '20.1094' '19.9624' '19.8239' '19.9350' '20.0156' '19.6740' '20.2968'
 '20.4626' '20.3365' '19.8814' '19.7007' '19.9279' '20.3834' '20.1204'
 '19.6706' '20.0567' '20.0080' '19.9550' '19.6589' '19.5776' '20.1670'
 '19.9517' '20.3510' '19.8044' '19.5278' '20.4368' '20.0038' '19.8679'
 '20.4252' '19.5264' '20.2749' '20.4239' '19.6160' '20.1313' '19.7657'
 '20.2859' '20.3822' '19.8211' '20.1081' '19.8631' '20.4326' '20.2479'
 '20.3392' '19.9177' '19.9083' '20.3750' '20.2954' '20.2105' '20.2462'
 '20.2692' '20.0874' '19.8345' '20.1164' '20.3417' '20.3657' '19.7464'
 '19.8499' '19.6164' '20.3049' '19.5554' '19.7320' '20.0337' '19.6462'
 '19.8875' '20.0540' '20.4274' '19.6446' '20.3571' '20.4294' '19.5811'
 '20.1996' '20.3537' '19.6303' '20.1521' '20.0754' '20.2037' '20.4463'
 '20.3688' '19.8993' '20.2203' '20.3795' '20.3851' '20.0423' '19.9114'
 '19.8570' '20.1280' '20.1033' '20.2863' '20.2042' '19.8783' '20.0807'
 '19.6757' '19.7570' '20.1768' '20.2991' '19.9710' '20.1159' '20.1179'
 '20.1016' '19.8604' '19.7200' '19.9700' '20.3983' '19.6659' '19.6377'
 '19.8948' '19.6908' '20.0626' '19.9999' '19.6493' '20.2095' '20.4180'
 '20.4284' '19.6700' '20.2742' '20.2831' '19.5703' '20.0309' '20.0636'
 '19.9728' '20.1340' '19.6242' '20.0461' '19.6693' '20.0973' '19.5383'
 '20.0665' '19.8295' '19.5070' '20.4675' '19.6517' '20.2283' '19.6741'
 '20.2248' '19.6525' '20.2436' '20.4504' '20.2551' '19.8516' '20.1409'
 '19.9685' '20.1837' '20.0091' '20.4204' '19.7133' '20.1017'
 '1.521216947917E12' '20.1507' '20.4415' '20.4050' '19.5368' '19.7254'
 '19.9065' '20.1692' '19.6352' '19.8740' '19.6619' '1.52121694927E12'
 '19.6090' '20.2087' '20.0539' '20.0867' '20.4343' '19.9007' '20.0514'
 '19.7375' '20.1661' '20.2529' '19.8052' '19.6816' '19.6473' '20.2642'
 '19.8853' '19.7036' '19.6195' '20.0635' '20.0965' '19.7322' '20.3892'
 '19.5001' '20.4356' '20.1434' '19.7979' '19.6282' '20.4100' '19.5290'
 '19.5344' '19.8318' '20.0668' '20.4430' '20.0727' '19.9010' '20.3733'
 '19.6384' '19.8959' '19.9349' '19.6287' '19.5438' '19.7925' '20.1953'
 '20.2813' '20.0276' '20.1145' '19.7124' '20.2319' '20.0820' '20.1681'
 '20.4005' '20.1508' '19.6737' '19.7696' '19.7108' '20.3729' '19.8547'
 '20.2747' '20.0244' '19.7350' '20.1444' '20.0898' '19.6587' '19.8374'
 '19.7253' '19.5685' '19.8383' '19.5757' '19.9406' '20.1509' '19.9490'
 '20.4893' '19.7257' '19.7179' '19.9346' '20.2917' '20.4175' '19.5562'
 '20.3687' '20.2182' '20.1510' '19.6219' '20.4170' '19.6210' '19.8863'
 '20.3441' '20.2172' '19.9615' '19.5499' '19.5602' '20.3403' '19.5951'
 '19.6503' '19.6277' '19.9740' '19.8129' '20.0438' '20.2661' '19.7712'
 '19.5577' '20.2360' '20.0116' '20.0828' '19.8168' '20.0127' '20.3707'
 '20.2581' '19.5319' '20.0740' '19.5408' '20.4568' '19.6699' '19.9034'
 '19.9476' '19.8277' '19.5379' '20.3405' '20.4757' '19.8356' '19.6124'
 '20.3720' '20.3071' '20.3036' '19.5567' '20.1972' '20.0062' '20.1487'
 '19.8643' '20.4260' '19.9076' '20.3786' '20.2100' '19.9043' '19.7694'
 '19.7831' '19.9739' '20.0210' '20.2592' '20.2569' '20.0928' '19.7046'
 '20.3271' '19.9309' '19.9853' '20.3097' '19.7175' '20.1816' '19.8200'
 '19.5833' '19.6553' '19.5210' '19.7281' '20.0837' '20.3577' '20.1676'
 '20.3020' '19.9411' '20.3354' '19.7933' '20.1666' '19.9167' '19.9284'
 '19.9348' '19.9045' '20.3330' '20.2756' '20.2247' '19.8877' '20.0732'
 '19.8215' '19.9617' '20.4496' '19.7763' '20.1037' '20.3763' '20.0390'
 '1.521216969706E12' '19.8711' '20.0139' '20.1367' '20.0404' '20.4727'
 '19.9032' '19.6677' '20.2155' '19.8820' '20.0545' '20.4530' '20.1852'
 '19.8762' '19.6439' '20.4639' '20.1977' '19.8458' '19.9082' '19.5350'
 '19.9840' '19.5445' '20.3594' '20.0562' '20.2417' '20.0147' '20.2833'
 '19.6443' '19.6809' '19.8154' '19.6636' '19.7384' '19.5055' '20.2448'
 '20.2706' '20.4853' '19.9835' '19.5777' '20.0476' '20.4195' '19.5812'
 '19.6835' '19.7315' '20.0317' '19.9683' '20.1638' '19.7636' '19.6411'
 '19.6603' '20.0148' '19.9908' '19.6680' '20.1498' '20.3495' '20.0964'
 '20.0906' '20.1357' '19.8471' '19.5566' '20.1887' '20.4696' '19.7250'
 '19.5679' '20.0084' '20.0132' '19.8223' '19.5203' '20.0203' '20.4436'
 '19.8741' '20.2703' '20.0465' '19.7429' '19.5912' '20.3282' '19.5376'
 '20.1405' '19.6405' '19.8773' '20.1116' '19.5257' '19.5926' '20.2690'
 '19.9573' '20.2870' '20.2746' '19.8380' '19.8519' '19.8845' '20.1003'
 '20.2236' '19.5713' '19.9809' '19.6325' '20.1813' '19.5898' '19.9183'
 '20.0282' '20.4086' '19.7243' '19.7332' '19.6818' '19.5677' '19.6721'
 '20.0167' '20.4160' '20.2481' '19.7847' '20.2493' '20.3181' '19.7458'
 '19.7974' '19.8411' '19.7295' '20.2304' '20.3251' '19.5274' '19.8718'
 '19.9101' '20.2687' '20.2802' '20.3337' '20.4131' '20.0075' '19.6684'
 '20.3361' '20.4304' '20.4734' '19.6930' '20.1018' '19.8291' '20.2165'
 '20.1273' '19.6562' '19.6765' '20.0724' '20.1746' '20.3526' '19.7194'
 '20.3102' '19.6640' '20.4200' '19.5550' '20.2259' '20.1105' '20.4218'
 '20.0912' '20.1544' '20.0793' '19.5170' '20.3004' '20.0388' '19.7511'
 '19.8025' '19.7386' '19.8114' '20.1386' '19.8943' '20.4739' '20.2853'
 '20.3797' '20.1872' '19.7481' '19.5601' '20.4082' '19.5382' '20.1671'
 '19.8498' '20.3667' '19.7082' '19.9565' '19.6868' '19.7110' '20.3061'
 '19.9415' '19.9521' '19.8217' '19.9659' '20.4938' '20.4657' '20.4423'
 '19.6063' '19.7437' '19.5975' '20.2045' '20.0383' '20.0039' '19.5990'
 '19.6571' '20.2636' '19.7392' '19.7741' '20.2644' '20.1382' '19.9443'
 '19.6330' '20.4364' '19.6726' '20.0900' '20.0217' '19.8573' '19.5154'
 '19.5931' '19.9181' '19.6429' '19.8056' '20.3480' '20.4266' '20.0880'
 '20.3933' '19.9760' '19.6831' '19.7405' '20.4470' '20.3651' '20.3874'
 '19.5012' '19.5089' '19.7406' '20.2393' '20.3531' '20.0482' '19.9503'
 '20.3783' '20.3056' '20.0996' '19.7886' '19.5152' '20.3766' '20.4615'
 '20.2077' '20.3408' '19.9556' '20.2550' '20.4365' '19.6145' '20.3592'
 '20.2723' '19.6184' '20.1229' '19.7255' '19.8382' '19.6305' '19.7213'

 Clean 'value' column

In [11]:
data['value'] = data['value'].astype(str).str.strip().str.lower()

data['value'] = data['value'].replace(
    ['none', 'null', 'nan', ''],
    np.nan
)

In [12]:
import re
JAVA_OBJ_REGEX = re.compile(r"^[a-zA-Z0-9_.]+@[a-f0-9]+$")

def detect_semantic_type(v):
    if v is None:
        return "missing"
    v = str(v).strip().lower()
    if v in ("none", "null", "nan", ""):
        return "missing"
    if v in ("true", "false"):
        return "boolean"
    if JAVA_OBJ_REGEX.match(v):
        return "java_object"

    # Try to parse as float to distinguish timestamp/float/integer
    try:
        f = float(v)
    except Exception:
        f = None

    if f is not None:
        # large numbers likely timestamp in ms
        if f > 1e11:
            return "timestamp_ms"
        # pure digit strings represent integers
        if v.isdigit():
            return "integer"
        # otherwise it's a float
        return "float"

    # fallback checks
    if v.isdigit():
        return "integer"
    return "string"

data["value_type"] = data["value"].apply(detect_semantic_type)
print(data["value_type"].value_counts())

value_type
integer         184469
float           130115
boolean          40426
missing           2156
timestamp_ms       575
string             200
java_object         11
Name: count, dtype: int64

Creation des features

In [13]:
#flags (type indicators)
for t in data['value_type'].unique():
    data[f'value_is_{t}'] = (data['value_type'] == t).astype(int)

In [14]:
data['value_int'] = np.nan
mask = data['value_type']=='integer'
data.loc[mask,'value_int'] = pd.to_numeric(data.loc[mask,'value'], errors='coerce')

data['value_float'] = np.nan
mask = data['value_type']=='float'
data.loc[mask,'value_float'] = pd.to_numeric(data.loc[mask,'value'], errors='coerce')

data['value_bool'] = np.nan
mask = data['value_type']=='boolean'
data.loc[mask,'value_bool'] = data.loc[mask,'value'].map({'true':1,'false':0})

# Timestamps
data['value_ts'] = pd.NaT
mask = data['value_type']=='timestamp_ms'
data.loc[mask,'value_ts'] = pd.to_datetime(pd.to_numeric(data.loc[mask,'value'], errors='coerce'), unit='ms', errors='coerce')
data['value_ts_hour'] = data['value_ts'].dt.hour
data['value_ts_minute'] = data['value_ts'].dt.minute

data['value_ts_hour'] = data['value_ts'].dt.hour
data['value_ts_minute'] = data['value_ts'].dt.minute

In [15]:
features_ext = [
    'value_int', 'value_float', 'value_bool',
    'value_ts', 'value_ts_hour', 'value_ts_minute'
]


type_flags = [col for col in data.columns if col.startswith('value_is_')]
print(type_flags)

display(data[features_ext + type_flags].head(10))

['value_is_missing', 'value_is_float', 'value_is_integer', 'value_is_timestamp_ms', 'value_is_boolean', 'value_is_java_object', 'value_is_string']

,value_int,value_float,value_bool,value_ts,value_ts_hour,value_ts_minute,value_is_missing,value_is_float,value_is_integer,value_is_timestamp_ms,value_is_boolean,value_is_java_object,value_is_string
0,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
1,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
2,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
3,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
4,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
5,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
6,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
7,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
8,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0
9,NaN,NaN,NaN,NaT,NaN,NaN,1,0,0,0,0,0,0

Extraction des features temporelles

In [16]:
data['datetime'] = pd.to_datetime(data['timestamp'], unit='ms', errors='coerce')
data['hour'] = data['datetime'].dt.hour
data['minute'] = data['datetime'].dt.minute
data['second'] = data['datetime'].dt.second
data['time_of_day'] = data['hour'] + data['minute']/60
data['is_night'] = data['hour'].apply(lambda h:1 if 22<=h or h<=6 else 0)

# Fill missing accessedNodeType
data['accessedNodeType'] = data['accessedNodeType'].fillna('unknown')

In [17]:
data['is_night'].value_counts()

is_night
0    238361
1    119591
Name: count, dtype: int64

In [18]:
time_features = ['datetime', 'hour', 'minute', 'second', 'time_of_day', 'is_night']

print(data[time_features].head(10))

                 datetime  hour  minute  second  time_of_day  is_night
0 2018-03-02 23:00:00.000    23       0       0         23.0         1
1 2018-03-02 23:00:03.269    23       0       3         23.0         1
2 2018-03-02 23:00:03.279    23       0       3         23.0         1
3 2018-03-02 23:00:03.290    23       0       3         23.0         1
4 2018-03-02 23:00:03.464    23       0       3         23.0         1
5 2018-03-02 23:00:03.464    23       0       3         23.0         1
6 2018-03-02 23:00:03.474    23       0       3         23.0         1
7 2018-03-02 23:00:03.474    23       0       3         23.0         1
8 2018-03-02 23:00:03.484    23       0       3         23.0         1
9 2018-03-02 23:00:04.212    23       0       4         23.0         1

In [19]:
# Afficher 10 lignes aléatoires
print(data[time_features].sample(10))

                      datetime  hour  minute  second  time_of_day  is_night
140377 2018-03-03 09:51:35.823     9      51      35     9.850000         0
218408 2018-03-03 14:41:08.512    14      41       8    14.683333         0
29609  2018-03-03 01:20:31.299     1      20      31     1.333333         1
47909  2018-03-03 02:41:23.680     2      41      23     2.683333         1
323153 2018-03-03 20:52:52.696    20      52      52    20.866667         0
158505 2018-03-03 11:07:04.002    11       7       4    11.116667         0
77509  2018-03-03 04:59:37.348     4      59      37     4.983333         1
236895 2018-03-03 15:49:19.684    15      49      19    15.816667         0
297797 2018-03-03 19:27:21.194    19      27      21    19.450000         0
210694 2018-03-03 14:12:36.757    14      12      36    14.200000         0

In [20]:
cols_to_show = [
    'datetime', 'hour', 'minute', 'second', 'time_of_day', 'is_night',
    'value_int', 'value_float', 'value_bool',
    'value_ts', 'value_ts_hour', 'value_ts_minute',
    'value_is_missing', 'value_is_float', 'value_is_integer', 'value_is_timestamp_ms', 'value_is_boolean', 'value_is_java_object', 'value_is_string',
    'sourceType', 'sourceLocation',
    'destinationServiceType', 'destinationLocation',
    'accessedNodeType', 'operation',
    'normality'
]

from IPython.display import display
display(data[cols_to_show].head(10))

,datetime,hour,minute,second,time_of_day,is_night,value_int,value_float,value_bool,value_ts,...,value_is_boolean,value_is_java_object,value_is_string,sourceType,sourceLocation,destinationServiceType,destinationLocation,accessedNodeType,operation,normality
0,2018-03-02 23:00:00.000,23,0,0,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/lightControler,BedroomParents,/lightControler,BedroomParents,/lightControler,registerService,0
1,2018-03-02 23:00:03.269,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/lightControler,Dinningroom,/lightControler,Dinningroom,/lightControler,registerService,0
2,2018-03-02 23:00:03.279,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/lightControler,BedroomChildren,/lightControler,BedroomChildren,/lightControler,registerService,0
3,2018-03-02 23:00:03.290,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/lightControler,Kitchen,/lightControler,Kitchen,/lightControler,registerService,0
4,2018-03-02 23:00:03.464,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/movementSensor,Kitchen,/movementSensor,Kitchen,/movementSensor,registerService,0
5,2018-03-02 23:00:03.464,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/sensorService,BedroomParents,/sensorService,BedroomParents,/sensorService,registerService,0
6,2018-03-02 23:00:03.474,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/movementSensor,BedroomParents,/movementSensor,BedroomParents,/movementSensor,registerService,0
7,2018-03-02 23:00:03.474,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/sensorService,Kitchen,/sensorService,Kitchen,/sensorService,registerService,0
8,2018-03-02 23:00:03.484,23,0,3,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/sensorService,BedroomChildren,/sensorService,BedroomChildren,/sensorService,registerService,0
9,2018-03-02 23:00:04.212,23,0,4,23.0,1,NaN,NaN,NaN,NaT,...,0,0,0,/movementSensor,BedroomChildren,/movementSensor,BedroomChildren,/movementSensor,registerService,0

In [21]:
# Count non-NaNs per column
print(data[['value_int','value_float','value_bool','value_ts']].notna().sum())

# Check type flags
data[[col for col in data.columns if col.startswith('value_is_')]].sum()

value_int      184469
value_float    130115
value_bool      40426
value_ts          575
dtype: int64

value_is_missing           2156
value_is_float           130115
value_is_integer         184469
value_is_timestamp_ms       575
value_is_boolean          40426
value_is_java_object         11
value_is_string             200
dtype: int64

Encodage des colonnes catégorielles

In [22]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = ['sourceType','sourceLocation','destinationServiceType','destinationLocation','accessedNodeType','operation']
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded = encoder.fit_transform(data[categorical_cols])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(categorical_cols))

# Tree-based dataset
data_tree = pd.concat([data.drop(columns=categorical_cols + ['value','timestamp','datetime','value_type']), encoded_df], axis=1)

In [23]:
display(data_tree.head(10))

,normality,value_is_missing,value_is_float,value_is_integer,value_is_timestamp_ms,value_is_boolean,value_is_java_object,value_is_string,value_int,value_float,...,accessedNodeType_/sensorService,accessedNodeType_/smartPhone,accessedNodeType_/thermostat,accessedNodeType_/washingService,accessedNodeType_unknown,operation_lockSubtree,operation_read,operation_registerService,operation_subscribe,operation_write
0,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,0,1,0,0,0,0,0,0,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7,0,1,0,0,0,0,0,0,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0,1,0,0,0,0,0,0,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,0,1,0,0,0,0,0,0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

Numeric imputation

In [24]:
from sklearn.impute import SimpleImputer
print(data[['value_int','value_float','value_bool','value_ts']].notna().sum())
numeric_features = ['value_int','value_float','value_bool','value_ts_hour','value_ts_minute','hour','minute','second','time_of_day','is_night']

# Tree-based: median
tree_imputer = SimpleImputer(strategy='median')
data_tree[numeric_features] = tree_imputer.fit_transform(data_tree[numeric_features])



# DL: fill missing numeric with 0
data_dl = data.drop(columns=['value','timestamp','datetime','value_type']).copy()
data_dl[numeric_features] = data_dl[numeric_features].fillna(0)

value_int      184469
value_float    130115
value_bool      40426
value_ts          575
dtype: int64

In [25]:
print(data_dl[['value_int','value_float','value_bool','value_ts']].isna().sum())

value_int           0
value_float         0
value_bool          0
value_ts       357377
dtype: int64

In [26]:
print(data_tree[['value_int','value_float','value_bool','value_ts']].isna().sum())

value_int           0
value_float         0
value_bool          0
value_ts       357377
dtype: int64

In [27]:
data_tree.drop(columns=[
    'value_ts','value_ts_hour','value_ts_minute'
], inplace=True)

data_dl.drop(columns=[
    'value_ts','value_ts_hour','value_ts_minute'
], inplace=True)

Categorical encoding for DL (embeddings)

In [28]:
from sklearn.preprocessing import LabelEncoder

data_dl_cat = data_dl[categorical_cols].copy()
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    data_dl_cat[col] = le.fit_transform(data_dl_cat[col])
    label_encoders[col] = le

# Drop original categorical columns and concat integer-encoded
data_dl = pd.concat([data_dl.drop(columns=categorical_cols), data_dl_cat], axis=1)

Normalize time features for DL

In [29]:
from sklearn.preprocessing import MinMaxScaler

normalize_cols = ['hour','minute','second','time_of_day']
scaler_minmax = MinMaxScaler()
data_dl[normalize_cols] = scaler_minmax.fit_transform(data_dl[normalize_cols])

Export datasets

In [30]:
data_tree.to_csv("data/data_processed_for_tree_models.csv", index=False)
data_dl.to_csv("data/data_processed_for_dl_models.csv", index=False)

print("Preprocessed datasets exported successfully!")

Preprocessed datasets exported successfully!

Résultat final

Features numériques / booléennes :
value_int, value_float, value_bool, value_is_missing, value_is_float, value_is_integer, 
value_is_timestamp_ms, value_is_boolean, value_is_java_object, value_is_string, 
value_ts_hour, value_ts_minute, hour, minute, second, time_of_day, is_night, 
delta_time_prev, delta_time_next

Features catégorielles encodées : toutes les colonnes node/opérations en OneHot

Label : normality

Vérifier les plages des features numériques

In [31]:
numeric_features = [
    'value_int', 'value_float',
    'hour', 'minute', 'second', 'time_of_day', 'is_night'
]

# afficher min, max, mean, std
data_tree[numeric_features].describe()

,value_int,value_float,hour,minute,second,time_of_day,is_night
count,357952.000000,357952.000000,357952.000000,357952.000000,357952.000000,357952.000000,357952.000000
mean,1.950222,19.965531,12.046693,29.453360,29.509937,12.537583,0.334098
std,2.494838,0.758331,6.772329,17.235144,17.283045,6.780850,0.471675
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,19.992900,6.000000,15.000000,14.000000,6.816667,0.000000
50%,1.000000,19.992900,13.000000,29.000000,30.000000,13.066667,0.000000
75%,1.000000,19.992900,18.000000,44.000000,44.000000,18.350000,1.000000
max,10.000000,38.571738,23.000000,59.000000,59.000000,23.983333,1.000000

In [32]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler


# Normalize time features
normalize_cols = [
    'hour', 'minute', 'second', 'time_of_day',
]

scaler_minmax = MinMaxScaler()
data_tree[normalize_cols] = scaler_minmax.fit_transform(data_tree[normalize_cols])

# Check the results
data_tree[normalize_cols].describe()

                hour         minute         second    time_of_day
count  357952.000000  357952.000000  357952.000000  357952.000000
mean        0.523769       0.499209       0.500168       0.522762
std         0.294449       0.292121       0.292933       0.282732
min         0.000000       0.000000       0.000000       0.000000
25%         0.260870       0.254237       0.237288       0.284225
50%         0.565217       0.491525       0.508475       0.544823
75%         0.782609       0.745763       0.745763       0.765115
max         1.000000       1.000000       1.000000       1.000000

data final :

value_numeric, delta_time_prev, delta_time_next	: Standardisées (mean=0, std=1)
hour, minute, second	: Normalisées [0,1]
value_bool, value_missing :	Binaires 0/1
Colonnes catégorielles  :	Encodées en nombres

In [33]:
display(data_tree.head(10))

,normality,value_is_missing,value_is_float,value_is_integer,value_is_timestamp_ms,value_is_boolean,value_is_java_object,value_is_string,value_int,value_float,...,accessedNodeType_/sensorService,accessedNodeType_/smartPhone,accessedNodeType_/thermostat,accessedNodeType_/washingService,accessedNodeType_unknown,operation_lockSubtree,operation_read,operation_registerService,operation_subscribe,operation_write
0,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,0,1,0,0,0,0,0,0,1.0,19.9929,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7,0,1,0,0,0,0,0,0,1.0,19.9929,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0,1,0,0,0,0,0,0,1.0,19.9929,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,0,1,0,0,0,0,0,0,1.0,19.9929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [34]:
data_tree.to_csv("data/data_processed_for_tree-based_models.csv", index=False)

print("Preprocessed data exported successfully!")

Preprocessed data exported successfully!